### ISSUE TITLE
First Attempt

### ISSUE THREAD

**Issue by KouroshKSH** [KouroshKSH/Java-GitHub-Explorer#7]
# Task
Implement a basic back-and-forth interaction between the user and the app via the terminal. The user will be asked to either:
1. log in
2. sign up

Based on the user's choice:
- they have to either enter the username and password and can enter or be rejected from entering the app (for now, it's a simple message in the terminal)
- or create a new account

## Structure
1. **User Class:**
   - A class representing a user with attributes like username, password, etc.
   - Methods to handle user-related operations like creating, validating, and fetching user details.

4. **Database Handler:**
   - A class responsible for interacting with the MongoDB database.
   - Methods to perform database operations like inserting a new user, querying users, etc.

5. **Main Class:**
   - A class that contains the main method to interact with users via the terminal.

## Steps to Implement
1. **User Class:**
   - Create a `User` class with attributes like `username`, `password`, etc.
   - Include methods to create a new user, check if a user exists, and validate passwords.

2. **Database Handler:**
   - Implement a class (`DatabaseHandler`, for instance) to handle interactions with MongoDB using appropriate libraries (like Spring Data MongoDB).
   - Include methods to insert a new user, query for users based on username, etc.

3. **Main Class:**
   - Write the main method in a separate class (`MainClass`, for example).
   - In the main method, create instances of `User` and `DatabaseHandler` classes.
   - Use `Scanner` to get user input from the terminal and provide choices for sign-up or login.
   - Based on the user's choice, prompt for necessary inputs (username, password).
   - Use methods from the `User` class to handle user-related operations (sign-up, login) and methods from the `DatabaseHandler` class to interact with the database.

## Code Skeleton
Here's a basic skeleton of how the classes might look:

```java
// User Class
public class User {
    private String username;
    private String password;
    
    // Constructor, getters, setters, etc.

    public void createUser(String username, String password) {
        // Implementation to create a new user
    }

    public boolean userExists(String username) {
        // Check if user exists in the database
    }

    public boolean validatePassword(String username, String password) {
        // Validate user password
    }
}

// Database Handler Class
public class DatabaseHandler {
    // MongoDB connection and setup

    public void insertUser(User user) {
        // Insert a new user into the database
    }

    public User getUserByUsername(String username) {
        // Get user details by username from the database
    }
}

// Main Class
public class MainClass {
    public static void main(String[] args) {
        User user = new User();
        DatabaseHandler dbHandler = new DatabaseHandler();
        
        // Logic for user interaction, sign-up, and login process
    }
}
```

This structure provides a basic outline to implement user sign-up, login, and interaction with the database. It's essential to add MongoDB connection setup, handle exceptions, and implement user input validation as needed. Each class is responsible for a specific set of functionalities, ensuring a clean and maintainable codebase.

**Comment by KouroshKSH** [comment]
- [x] done with the package and class for `DatabaseHandler` 

To Do:
- [ ] `User`
- [ ] `UserInteraction`

**Comment by KouroshKSH** [comment]
- [x] done with the package and class for `User`
- [x] enhance the `DatabaseHandler` to check user's existence (given a username to check within the DB) and also said user's password (if it matches the saved password for that user in the DB)

To Do:
- [ ] `UserInteraction`

**Comment by KouroshKSH** [comment]
In user interaction:
- [x] log-in and sign-up procedures
- [ ] displaying repositories

**Comment by KouroshKSH** [comment]
- [x] a number of examples to print the repositories based on different queries:

```java
// in UserInteractionHandler.java
// in signUp()
        DatabaseHandler dbHandler = new DatabaseHandler();
        
        System.out.println("\n> Printing a list 4 of random repositories:\n");
        List<Document> result = dbHandler.getRandomRepositories(4);
        dbHandler.printRepositories(result);
        
        System.out.println("\n> Printing the list of repositories that have more than 100'000 stars:\n");
        result = dbHandler.filterReposWithStarsGEQ(100000);
        dbHandler.printRepositories(result);
        
        System.out.println("\n> Let's see if `awesome-neovim` exists in the database. If so, print its information.\n");
        result = dbHandler.findRepoByTitle("awesome-neovim");
        dbHandler.printRepositories(result);
        
        System.out.println("\n> Let's see if `lazygit` exists in the database. If so, print its information.\n");
        result = dbHandler.findRepoByTitle("lazygit");
        dbHandler.printRepositories(result);
```
